name: Check
on:
  push:
    branches:
      - main
      - open_file_branch
      - print_values
  pull_request:
    branches:
      - main
      - open_file_branch
      - print_values

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install py
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake
        run: flake8 .
      - name: Run mypy
        run: mypy .
      - name: Test pytest
        run: |
          pytest --html=report.html --self-contained-html
        env:
          PYTHONPATH: ${{github.workspace}}
      - name: Archive HTML report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html